#pragma once

typedef enum HTTP_METHOD {
    HTTP_METHOD_GET,
    HTTP_METHOD_PROPFIND,
    HTTP_METHOD_OPTIONS,
    HTTP_METHOD_PUT,
    HTTP_METHOD_DELETE,
    HTTP_METHOD_HEAD,
    HTTP_METHOD_MKCOL,
    HTTP_METHOD_LOCK,
    HTTP_METHOD_UNLOCK,
    HTTP_METHOD_MOVE,
    HTTP_METHOD_UNKNOWN
} HTTP_METHOD;

HTTP_METHOD http_method_from_str(char * method);

static char * HTTP_METHOD_STRINGS[] = {"GET", "PROPFIND", "OPTIONS", "PUT", "DELETE", "HEAD", "MKCOL", "LOCK","UNLOCK", "MOVE", "UNKNOWN"};